import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/navbar";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Coder Adventures - A World of Education",
    description: "Generated by create next app",
    icons: "https://i.postimg.cc/zvvGXfMY/palmTree.png"
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
            <body className={poppins.className + " h-full"}>
                {children}
            </body>
        </html>
    );
}